name: Deploy Lab 5 - Key Vault Integration

on:
  push:
    paths:
      - 'Bicep Labs/05-KeyVault/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy-keyvault-lab:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create Resource Group
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az group create --name toy-keyvault-lab-rg --location westus3

      
      - name: Deploy Bicep Template
        uses: azure/arm-deploy@v1
        with:
          resourceGroupName: toy-keyvault-lab-rg
          template: ./Bicep Labs/05-KeyVault/new.bicep
          parameters: ./Bicep Labs/05-KeyVault/new.parameters.dev.json
          failOnStdErr: false
